version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}web
    container_name: api
    hostname: api
    ports:
      - "6001:80"
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=LocalDocker
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: db
    hostname: db
    environment:
      - SA_PASSWORD=ThisPasswordIsOnlyForLocalUse1!
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"